#!/usr/bin/env python3
"""Generate the two published artifacts from STANDARD.md.

STANDARD.md holds the rules. This script wraps them in the frontmatter and the
target-selection block each format needs, and writes:

    plugins/spare-me/commands/spare-me.md   Claude Code slash command
    skills/spare-me/SKILL.md                portable Agent Skill (Codex, Cursor)

Both outputs are committed, because the plugin marketplace and the README's curl
install each fetch a real file. Never edit them by hand; edit STANDARD.md and run
this script.

    python3 build.py            write the artifacts
    python3 build.py --check    exit 1 if either artifact is out of date
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).parent
STANDARD = ROOT / "STANDARD.md"
COMMAND = ROOT / "plugins/spare-me/commands/spare-me.md"
SKILL = ROOT / "skills/spare-me/SKILL.md"

BANNER = "<!-- GENERATED FROM STANDARD.md — do not edit this file. Edit STANDARD.md, run build.py. -->"

SHORT_DESC = (
    "Rewrite the previous reply — or any text you point at — per the Agent "
    "Communication Standard"
)

SKILL_DESC = (
    "Rewrite an AI agent's previous reply, a selected passage, a file's prose, or "
    "pasted text into clear, direct language without changing its meaning. Preserve "
    "every fact, number, command, file path, caveat, and uncertainty. Use only when "
    "the user explicitly invokes or asks for Spare Me; do not apply it automatically "
    "to ordinary editing requests."
)

# The one thing the two formats genuinely differ on: how the target is named.
COMMAND_TARGET = """Apply the Agent Communication Standard below to a target text.

**Target:** $ARGUMENTS

- If the target above is empty: rewrite your own previous reply.
- If it names a part of the previous reply (e.g. "the part about X"): rewrite only that part.
- If it is a file path: read the file and rewrite its prose. Leave code blocks unchanged except for
  their comments. Show the rewrite; edit the file only if the user asked you to.
- If it is pasted text or a draft: rewrite that text.
"""

SKILL_TARGET = """# Spare Me

Rewrite the target so a reader can understand it on the first pass. Apply the Agent Communication
Standard below.

## Choose the target

- With no supplied text, rewrite the previous assistant reply.
- When the user names a part of the previous reply, rewrite only that part.
- For a file path, read the file and rewrite its prose. Leave code blocks unchanged except for
  their comments. Show the rewrite; edit the file only when the user asks.
- Otherwise, rewrite the pasted text or draft.
"""


def body() -> str:
    """The shared rules, with STANDARD.md's own title and build comment stripped."""
    lines = STANDARD.read_text(encoding="utf-8").split("\n")
    start = next(i for i, l in enumerate(lines) if l.startswith("## "))
    return "\n".join(lines[start:]).strip() + "\n"


def command_artifact() -> str:
    return (
        "---\n"
        f"description: {SHORT_DESC}\n"
        "---\n"
        f"{BANNER}\n\n"
        f"{COMMAND_TARGET}\n"
        "# Agent Communication Standard\n\n"
        f"{body()}"
    )


def skill_artifact() -> str:
    return (
        "---\n"
        "name: spare-me\n"
        f"description: {SKILL_DESC}\n"
        "---\n"
        f"{BANNER}\n\n"
        f"{SKILL_TARGET}\n"
        "# Agent Communication Standard\n\n"
        f"{body()}"
    )


def main() -> int:
    targets = [(COMMAND, command_artifact()), (SKILL, skill_artifact())]
    if "--check" in sys.argv:
        stale = [p.name for p, text in targets if p.read_text(encoding="utf-8") != text]
        if stale:
            print("Out of date: " + ", ".join(stale) + ". Run: python3 build.py")
            return 1
        print("Both artifacts match STANDARD.md.")
        return 0
    for path, text in targets:
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
